/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.xtext.example.mydsl.generator.MyDslOutputConfigurationProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
	
	public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
		return MyDslOutputConfigurationProvider.class;
	}
}
